function deletedcode
%octrun checkbox uicontrols and callbacks

saveOCT_checkbox=uicontrol('Style','checkbox','Units','Normalized','Position',...
        [0.45 0.26 0.15 0.025],'String','OCT image','HorizontalAlignment',textAlignment,...
        'FontName',textFont,'Fontsize',checkboxFontsize,'Fontweight',textWeight,...
        'BackgroundColor',patchColour,'Callback',{@save_checkbox_CALLBACK); 
function saveOCT_CALLBACK(src,evt)
        saveOCT = get(src,'value');
end
    
saveImage_masked_checkbox=uicontrol('Style','checkbox','Units','Normalized','Position',...
        [0.45 0.235 0.15 0.025],'String','Att. image (masked)','HorizontalAlignment',textAlignment,...
        'Value',saveImage_masked,'FontName',textFont,'Fontsize',checkboxFontsize,'Fontweight',textWeight,...
        'BackgroundColor',patchColour,'Callback',@saveImage_masked_CALLBACK); 
function saveImage_masked_CALLBACK(src,evt)
        saveImage_masked = get(src,'value');
end 

saveImage_unmasked_checkbox=uicontrol('Style','checkbox','Units','Normalized','Position',...
        [0.45 0.21 0.15 0.025],'String','Att. image (unmasked)','HorizontalAlignment',textAlignment,...
        'FontName',textFont,'Fontsize',checkboxFontsize,'Fontweight',textWeight,...
        'BackgroundColor',patchColour,'Callback',@saveImage_unmasked_CALLBACK); 
function saveImage_unmasked_CALLBACK(src,evt)
        saveImage_unmasked = get(src,'value');
end

saveMu_masked_checkbox=uicontrol('Style','checkbox','Units','Normalized','Position',...
        [0.45 0.185 0.15 0.025],'String','Mu matrix (masked)','HorizontalAlignment',textAlignment,...
        'FontName',textFont,'Fontsize',checkboxFontsize,'Fontweight',textWeight,...
        'BackgroundColor',patchColour,'Callback',@saveMu_masked_CALLBACK); 
function saveMu_masked_CALLBACK(src,evt)
        saveMu_masked = get(src,'value');
end

saveMu_unmasked_checkbox=uicontrol('Style','checkbox','Units','Normalized','Position',...
        [0.45 0.16 0.15 0.025],'String','Mu matrix (unmasked)','HorizontalAlignment',textAlignment,...
        'FontName',textFont,'Fontsize',checkboxFontsize,'Fontweight',textWeight,...
        'BackgroundColor',patchColour,'Callback',@saveMu_unmasked_CALLBACK); 
function saveMu_unmasked_CALLBACK(src,evt)
        saveMu_unmasked = get(src,'value');
end

end